### PR TITLE
fix(exists-method): fix method syntax with an alias

### LINKED ISSUE #363: Fix: update index.exists method syntax
`index.exists` method returns a boolean and thus should have the following syntax => `index.exists?`. Create an alias to fix this.

### PR DESCRIPTION
**Pull request by chloelbn**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #363
| Need Doc update   | no

### CODE REVIEW

File: lib/algolia/index.rb [hunk 1]
```diff
@@ -1295,6 +1295,11 @@ def exists
       return true
     end
 
+    #
+    # Aliases the exists method
+    #
+    alias exists? exists
```
Comment (raphi) [inline lib/algolia/index.rb]: It's valid, I just have a preference for `alias :exists? :exists` as it shows a clear reference to a method. But this is nitpicking.

File: spec/client_spec.rb [hunk 2]
```diff
@@ -177,12 +177,12 @@ def wait_global_key_missing(key)
 
   it "should tell if index exists" do
     @index.add_object!({ :name => "John Doe", :email => "john@doe.org" }, "1")
-    expect(@index.exists).to be true
+    expect(@index.exists?).to be true
```
Comment (raphi) [inline spec/client_spec.rb]: Do we want to test both since both are valid?

File: lib/algolia/index.rb (hunk 1 above)
Comment (chloelbn) [reply lib/algolia/index.rb]: I thought that you had to use the `:` only with `alias_method`. Would you favor `alias_method`?

File: spec/client_spec.rb (hunk 2 above)
Comment (chloelbn) [reply spec/client_spec.rb]: I thought that only `exists?` would need to be tested since this is the recommended usage. what do you think?

File: lib/algolia/index.rb (hunk 1 above)
Comment (raphi) [reply lib/algolia/index.rb]: There are slight differences between the two of them but in this case both works. No the `:` works as well for `alias`

File: spec/client_spec.rb (hunk 2 above)
Comment (raphi) [reply spec/client_spec.rb]: Up to your team's good practices, how do you do in other clients?
